// front-end-vue/src/components/TheHeader.vue
<script setup></script>

<template>
  <section class="hero is-primary has-text-white mb-4">
    <div class="hero-body">
      <p class="title has-text-white">Food Delivery (Vue)</p>
      <p class="subtitle is-italic has-text-right">
        (...) sample front-end Single Page App
      </p>
    </div>
  </section>
</template>

// front-end-svelte/src/lib/TheHeader.svelte
<section class="hero is-svelte has-text-white mb-4">
    <div class="hero-body">
        <p class="title has-text-white">Food Delivery (Svelte)</p>
        <p class="subtitle is-italic has-text-right">(...) sample front-end Single Page App</p>
    </div>
</section>

<style>
   .is-svelte {
       background-color: #ff3e00
   }
</style>
