// front-end-vue/src/components/UserNavBar.vue
<script setup>
import { useAuthStore } from "@/stores/auth";

const authStore = useAuthStore();
</script>

<template>
  <section class="is-flex is-justify-content-end">
    <button
      v-if="authStore.isAuth"
      class="button is-warning"
      @click="authStore.signOut"
    >
      ⤴
    </button>
    <RouterLink v-else class="icon-text" to="/sign-in">
      <div class="box icon">🔑</div>
    </RouterLink>
  </section>
</template>

// front-end-svelte/src/lib/UserNavBar.svelte
<script>
	import { authStore, isAuth } from '../stores/auth.store.js';
</script>

<section class="is-flex is-justify-content-end	">
    {#if $isAuth}
        <button class="button is-warning" on:click={() => authStore.signOut()} > ⤴</button>
    {:else }
    <a class="icon-text" href="/sign-in">
        <div class="box icon">🔑</div>
    </a>
    {/if}
</section>
