// front-end-react/src/components/MainMenu.jsx
import { NavLink } from 'react-router-dom';

export function MainMenu() {

    const restaurants = [
        {id: 1, name: 'Food fest'},
        {id: 2, name: 'Burger to go'}
    ];
    const orders = [
        {id: 1, date: '02/09'},
        {id: 2, date: '31/08'}
    ];

	return <aside><p className="menu-label">Restaurants</p>
      <ul className="menu-list">
          {
              restaurants.map(restaurant => <li key={restaurant.id}>
                  <NavLink to={`/restaurant/${restaurant.id}`}>{restaurant.name}</NavLink>
              </li>)
          }
      </ul>
      <p className="menu-label">Orders</p>
      <ul className="menu-list">
          {
              orders.map(order => <li key={order.id}>
                <NavLink to={`/order/${order.id}`}>{order.date}</NavLink>
              </li>)
          }
      </ul>
  </aside>;
}

// front-end-angular/src/app/main-menu/main-menu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main-menu',
  template: `
    <aside>
      <p class="menu-label">Restaurants</p>
      <ul class="menu-list">
        <li *ngFor="let restaurant of restaurants">
          <a [routerLink]="'/restaurants/' + restaurant.id">{{restaurant.name}}</a>
        </li>
      </ul>
      <p class="menu-label">Orders</p>
      <ul class="menu-list">
        <li *ngFor="let order of orders">
          <a [routerLink]="'/orders/' + order.id">{{order.date}}</a>
        </li>
      </ul>
    </aside>
  `,
  styles: [
  ]
})
export class MainMenuComponent implements OnInit {

  restaurants = [
    {id: 1, name: 'Sea food restaurant'},
    {id: 2, name: 'Sooo Fast'}
  ]

  orders = [
    {id: 1, date: '01/09'},
    {id: 2, date: '14/09'}
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
