// front-end-react/src/App.js
import './App.css';
import { Route, Routes } from 'react-router-dom';
import { Header } from './components/Header';
import { HomePage } from './components/HomePage';
import { MainMenu } from './components/MainMenu';
import { RestaurantPage } from './components/RestaurantPage';
import { OrderPage } from './components/OrderPage';
import { SignInPage } from './components/SignInPage';
import { UserNavBar } from './components/UserNavBar';

function App() {
  return (
    <main className="container">
      <Header />
      <UserNavBar />
      <div className="columns">
        <div className="column is-2">
          <MainMenu />
        </div>
        <div className="column">
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="restaurant/:id" element={<RestaurantPage />} />
            <Route path="order/:id" element={<OrderPage />} />
            <Route path="sign-in" element={<SignInPage />} />
          </Routes>
        </div>
      </div>
    </main>
  );
}

export default App;

// front-end-vue/src/App.vue
<script setup>
import TheHeader from "@/components/TheHeader.vue";
import TheMenu from "@/components/TheMenu.vue";
import UserNavBar from "@/components/UserNavBar.vue";
import { RouterView } from "vue-router";
</script>

<template>
  <main class="container">
    <TheHeader />
    <UserNavBar />
    <div class="columns">
      <div class="column is-2">
        <TheMenu />
      </div>
      <div class="column">
        <RouterView />
      </div>
    </div>
  </main>
</template>
