// front-end-angular/src/app/home/main-menu.component.ts
import { HttpErrorResponse } from '@angular/common/http'
import { Component, OnInit } from '@angular/core';
import { Order } from '../restaurant/order'
import { OrdersService } from '../restaurant/orders.service'
import { Restaurant } from '../restaurant/restaurant'
import { RestaurantsService } from '../restaurant/restaurants.service'

@Component({
  selector: 'app-main-menu',
  template: `
    <aside>
      <p class="menu-label">Restaurants</p>
      <ul class="menu-list">
        <li *ngFor="let restaurant of restaurants">
          <a [routerLink]="'/restaurants/' + restaurant.id">{{restaurant.name}}</a>
        </li>
      </ul>
      <p class="menu-label">Orders</p>
      <ul class="menu-list">
        <li *ngIf="isOrdersLoading">
            <app-notification message="Orders loading.."></app-notification>
        </li>
        <li *ngIf="ordersErrorMessage">
          <app-notification [message]="ordersErrorMessage" type="danger"></app-notification>
        </li>
        <li *ngFor="let order of orders">
          <a [routerLink]="'/orders/' + order.id">{{order.date}}</a>
        </li>
      </ul>
    </aside>
  `,
  styles: [
  ]
})
export class MainMenuComponent implements OnInit {

  restaurants: Restaurant[] = []

  isOrdersLoading = false
  ordersErrorMessage = ''
  orders: Order[] = [ ]

  constructor(private restaurantsService: RestaurantsService, private ordersService: OrdersService) { }

  ngOnInit(): void {
    this.restaurantsService.getAll().subscribe((restaurants) => {
         this.restaurants = restaurants
    })

    this.isOrdersLoading = true
    this.ordersService.getAll().subscribe({
      next: (orders) => {
        this.orders = orders
        this.isOrdersLoading = false
      },
      error: (err: HttpErrorResponse) => {
        this.ordersErrorMessage = err.error?.message || err.message
        this.isOrdersLoading = false
      }
    })
  }

}

// front-end-react/src/components/MainMenu.jsx
import { useQuery } from '@tanstack/react-query';
import { NavLink } from 'react-router-dom';
import { ordersResource } from '../resources/orders.resource';
import { restaurantsResource } from '../resources/restaurants.resource';
import { Notification } from './Notification';

export function MainMenu() {

    // let restaurants = [];
    const {isLoading, error, isError, data: restaurants} = useQuery(['restaurants'], restaurantsResource.getAll)

    const {isLoading: isOrdersLoading, error: ordersError, data: orders} = useQuery(['orders'], ordersResource.getAll)



	return <aside><p className="menu-label">Restaurants</p>
      <ul className="menu-list">
          {
            isLoading &&
            <Notification message="Loading..." />
          }
          {
            isError &&
            <Notification type="danger" message={error.message} />
          }
          {
            restaurants &&
              restaurants.map(restaurant => <li key={restaurant.id}>
                  <NavLink to={`/restaurant/${restaurant.id}`}>{restaurant.name}</NavLink>
              </li>)
          }
      </ul>
      <p className="menu-label">Orders</p>
      <ul className="menu-list">
        {
          isOrdersLoading &&
          <Notification message="Loading..." />
        }
        {
          ordersError &&
          <Notification type="danger" message={ordersError.message} />
        }
          {
            orders &&
              orders.map(order => <li key={order.id}>
                <NavLink to={`/order/${order.id}`}>{order.date}</NavLink>
              </li>)
          }
      </ul>
  </aside>;
}
