// front-end-angular/src/app/auth/sign-in-page/sign-in-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  template: `
    <section>
      <h3 class="is-size-3 my-3">Sign to place the Order</h3>
      <form method="get" action="signed">
        <div class="field"><label class="label">E-mail</label>
          <div class="control"><input name="email" class="input" type="email"
                                      placeholder="Your e-mail"></div>
        </div>
        <div class="field"><label class="label">Password</label>
          <div class="control"><input name="password" class="input" type="password"
                                      placeholder="Your password"></div>
        </div>
        <div class="field">
          <div class="control">
            <button class="button is-link" type="submit">Sign in</button>
          </div>
        </div>
      </form>
    </section>
  `,
  styles: [
  ]
})
export class SignInPageComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

// front-end-react/src/components/SignInPage.jsx
export function SignInPage() {

	const handleSubmit = (ev) => ev.preventDefault()

	return <section><h3 className="is-size-3 my-3">Sign to place the Order</h3>
		<form onSubmit={handleSubmit}>
			<div className="field"><label className="label">E-mail</label>
				<div className="control"><input name="email" className="input" type="email"
				                                placeholder="Your e-mail" /></div>
			</div>
			<div className="field"><label className="label">Password</label>
				<div className="control">
					<input name="password" className="input" type="password"
				                                placeholder="Your password" />
				</div>
			</div>
			<div className="field">
				<div className="control">
					<button className="button is-link" type="submit">Sign in</button>
				</div>
			</div>
		</form>
	</section>;
}
