// front-end-svelte/src/lib/UserNavBar.svelte
<script>
	import { authStore, isAuth } from '../stores/auth.store.js';
</script>

<section class="is-flex is-justify-content-end	">
    {#if $isAuth}
        <button class="button is-warning" on:click={() => authStore.signOut()} > ⤴</button>
    {:else }
    <a class="icon-text" href="/sign-in">
        <div class="box icon">🔑</div>
    </a>
    {/if}
</section>

// front-end-react/src/components/UserNavBar.jsx
import { useContext } from "react";
import { Link } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";

export function UserNavBar() {
  const { isAuth, signOut } = useContext(AuthContext);

  return (
    <section className="is-flex is-justify-content-end	">
      {
        isAuth ?
          <button className="button is-warning" onClick={() => signOut()}> ⤴ </button>
          :
          <Link className="icon-text" to="/sign-in">
            <div className="box icon">🔑</div>
          </Link>
      }
    </section>
  );
}
