// front-end-svelte/src/lib/TheMenu.svelte
<script>
	import { isActive, url } from '@roxi/routify'
    import { useQuery } from '@sveltestack/svelte-query';
		import { formatDate } from '../date.helper.js';
    import { useOrdersQuery } from '../queries/useOrdersQuery.js';
    import { restaurantsResource } from '../resources/restaurants.resource.js';
    import Notification from './Notification.svelte';

    const restaurantsResult = useQuery(["restaurants"], restaurantsResource.getAll)
    const ordersResult = useOrdersQuery()

    $: ({ isLoading, isError, data, error } = $ordersResult)
</script>

<aside><p class="menu-label">Restaurants</p>
    <ul class="menu-list">
        {#if $restaurantsResult.isLoading }
            <li>
                <Notification message="Loading restaurants..." />
            </li>
        {:else if $restaurantsResult.isError}
            <li>
                <Notification message={$restaurantsResult.error.message} type="danger" />
            </li>
        {:else}
            {#each $restaurantsResult.data as {id, name}}
                {@const link = `/restaurants/${id}`}
                <li>
                    <a class:is-active={$isActive(link)} href={$url(link)}>{name}</a>
                </li>
            {/each}
        {/if}
    </ul>
    <p class="menu-label">Orders</p>
    <ul class="menu-list">
        {#if isLoading }
            <li>
                <Notification message="Loading orders..." />
            </li>
        {:else if isError}
            <li>
                <Notification error={error} type="danger" />
            </li>
        {:else}
            {#each data as {id, date}}
                {@const link = `/orders/${id}`}
                <li>
                    <a class:is-active={$isActive(link)} href={$url(link)}>{formatDate(date)}</a>
                </li>
            {/each}
        {/if}
    </ul>
</aside>

// front-end-vue/src/components/TheMenu.vue
<script setup>
import NotificationBox from "@/components/NotificationBox.vue";
import { formatDate } from "@/date.helper";
import { useOrdersQuery } from "@/queries/useOrdersQuery";
import { restaurantsResource } from "@/resources/restaurants.resource";
import { useQuery } from "vue-query";
import { RouterLink } from "vue-router";

const {
  isLoading,
  error,
  isError,
  data: restaurants,
} = useQuery(["restaurants"], restaurantsResource.getAll);

const { isOrdersLoading, ordersError, orders } = useOrdersQuery();
</script>

<template>
  <aside>
    <p class="menu-label">Restaurants</p>
    <ul class="menu-list">
      <li v-if="isLoading">
        <NotificationBox message="Loading..." />
      </li>
      <li v-if="isError">
        <NotificationBox :message="error.message" type="danger" />
      </li>
      <li v-for="restaurant of restaurants" :key="restaurant.id">
        <RouterLink
          activeClass="is-active"
          :to="`/restaurants/${restaurant.id}`"
        >
          {{ restaurant.name }}
        </RouterLink>
      </li>
    </ul>
    <p class="menu-label">Orders</p>
    <ul class="menu-list">
      <li v-if="isOrdersLoading">
        <NotificationBox message="Loading orders..." />
      </li>
      <li v-if="ordersError">
        <NotificationBox :message="ordersError.message" type="danger" />
      </li>
      <li v-for="order of orders" :key="order.id">
        <RouterLink activeClass="is-active" :to="`/orders/${order.id}`">
          {{ formatDate(order.date) }}
        </RouterLink>
      </li>
    </ul>
  </aside>
</template>

<style scoped>
.menu-list a.is-active {
  background-color: #00d1b2;
}
</style>
