// front-end-angular/src/app/home/user-nav-bar.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../auth/auth.service'

@Component({
  selector: 'app-user-nav-bar',
  template: `
    <section class="is-flex is-justify-content-end">
      <button *ngIf="authService.isAuth$ | async; else signIn"
              class="button is-warning"
              (click)="authService.singOut()">⤴</button>
      <ng-template #signIn>
        <a class="icon-text" routerLink="/sign-in">
          <div class="box icon">🔑</div>
        </a>
      </ng-template>
    </section>
  `,
  styles: [
  ]
})
export class UserNavBarComponent {

  constructor(public authService :AuthService) { }
}

// front-end-vue/src/components/UserNavBar.vue
<script setup>
import { useAuthStore } from "@/stores/auth";

const authStore = useAuthStore();
</script>

<template>
  <section class="is-flex is-justify-content-end">
    <button
      v-if="authStore.isAuth"
      class="button is-warning"
      @click="authStore.signOut"
    >
      ⤴
    </button>
    <RouterLink v-else class="icon-text" to="/sign-in">
      <div class="box icon">🔑</div>
    </RouterLink>
  </section>
</template>
